mysql_db:
  image: mysql:5.7.22
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root

api:
  build: ./api
  ports:
    - "5000:5000"
    - "8088:8088"
  environment:
    DATABASE_ENGINE: mysql
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: root
    DATABASE_NAME: queue_management
    DATABASE_PORT: 3306
    DATABASE_HOST: mysql_db
    THEQ_SNOWPLOW_CALLFLAG: "false"
  links:
    - mysql_db

frontend:
  build: ./frontend
  ports:
    - "8080:8080"



